### ISSUE TITLE
Diagramming tool inquire

### ISSUE THREAD

**Issue by ifree** [David-DiGioia/vulkan-diagrams#1]
Hi David, 
Thanks for your comprehensive diagrams for Vulkan mechanisms!
It's amazing to know to draw it like you, through I know some basic Inkscape drawing features but your work is far more than me, could you please share me some tricks to draw such nice diagrams with Inkscape(or ?)? 

Thank you very much.

**Comment by David-DiGioia** [comment]
Hi ifree, thanks for the nice comment. You're correct, I do use Inkscape. Some tips that make the software a lot easier to use for me:
- use `ctrl + c` to copy an object like normal, then you can select a different object and press `ctrl + shift + c` to paste only the style to the new object. I use this often, to change styles of the arrows for example.
- a setting I always disable is edit > preferences > behavior > transforms > scale stroke width. This way I can resize boxes without needing to fix the width of their stroke.
- I copy and paste a lot. Whenever I start a new diagram I copy a previous one, that way I can use all the same styling/fonts/etc by using the trick I mentioned in the first bullet point
